import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Header from "../components/Header";
import Gallery from "../components/Gallery";
import About from "../components/About";
import AnotherGallery from "../components/AnotherGallery";
import Slider from "../components/Slider";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header />
      <Gallery />
      <About />
      <AnotherGallery />
      <Slider />
    </div>
  );
};

export default Home;
